; robo2.bas - Kattava RoboBASIC testisarja kaikille komennoille
; Testaa kaikkien komentojen kaikki variantit

START:
  PRINT Robotti alkaa testiohjelmasta
  SET TARGET 15 15
  PRINT Asetettu kohde 1515

MOVETEST:
  PRINT Testattava MOVING ehto
  IF MOVING GOTO MOVINGON
  PRINT MOVING on false
  GOTO DIRTEST
  
MOVINGON:
  PRINT MOVING on true

DIRTEST:
  PRINT Testaa suuntakaskyt
  UP
  DOWN
  LEFT
  RIGHT
  UP 3
  DOWN 2
  LEFT 5
  RIGHT 4

TARGETTEST:
  PRINT Testaa SET TARGET
  SET TARGET 10 10
  SET TARGET 5 5

CONDTEST:
  PRINT Testaa ehdot
  IF AT TARGET GOTO ATTARGETTRUE
  PRINT AT TARGET false
  GOTO NOTTARGETTEST
  
ATTARGETTRUE:
  PRINT AT TARGET true
  
NOTTARGETTEST:
  IF NOT AT TARGET GOTO NOTTARGETTRUE
  PRINT NOT AT TARGET false
  GOTO HAVETARGETTEST
  
NOTTARGETTRUE:
  PRINT NOT AT TARGET true
  
HAVETARGETTEST:
  IF HAVE TARGET GOTO HAVETARGETTRUE
  PRINT HAVE TARGET false
  GOTO NOTHAVETARGETTEST
  
HAVETARGETTRUE:
  PRINT HAVE TARGET true
  
NOTHAVETARGETTEST:
  IF NOT HAVE TARGET GOTO NOTHAVETARGETTRUE
  PRINT NOT HAVE TARGET false
  GOTO LOADINGTEST
  
NOTHAVETARGETTRUE:
  PRINT NOT HAVE TARGET true

LOADINGTEST:
  PRINT Testaa LOADING ehto
  IF LOADING GOTO LOADINGTRUE
  PRINT LOADING false
  GOTO NOTLOADINGTEST
  
LOADINGTRUE:
  PRINT LOADING true
  
NOTLOADINGTEST:
  IF NOT LOADING GOTO NOTLOADINGTRUE
  PRINT NOT LOADING false
  GOTO UNLOADINGTEST
  
NOTLOADINGTRUE:
  PRINT NOT LOADING true

UNLOADINGTEST:
  PRINT Testaa UNLOADING ehto
  IF UNLOADING GOTO UNLOADINGTRUE
  PRINT UNLOADING false
  GOTO NOTUNLOADINGTEST
  
UNLOADINGTRUE:
  PRINT UNLOADING true
  
NOTUNLOADINGTEST:
  IF NOT UNLOADING GOTO NOTUNLOADINGTRUE
  PRINT NOT UNLOADING false
  GOTO FULLTEST
  
NOTUNLOADINGTRUE:
  PRINT NOT UNLOADING true

FULLTEST:
  PRINT Testaa FULL ehto
  IF FULL GOTO FULLTRUE
  PRINT FULL false
  GOTO NOTFULLTEST
  
FULLTRUE:
  PRINT FULL true
  
NOTFULLTEST:
  IF NOT FULL GOTO NOTFULLTRUE
  PRINT NOT FULL false
  GOTO EMPTYTEST
  
NOTFULLTRUE:
  PRINT NOT FULL true

EMPTYTEST:
  PRINT Testaa EMPTY ehto
  IF EMPTY GOTO EMPTYTRUE
  PRINT EMPTY false
  GOTO NOTEMPTYTEST
  
EMPTYTRUE:
  PRINT EMPTY true
  
NOTEMPTYTEST:
  IF NOT EMPTY GOTO NOTEMPTYTRUE
  PRINT NOT EMPTY false
  GOTO BLOCKEDTEST
  
NOTEMPTYTRUE:
  PRINT NOT EMPTY true

BLOCKEDTEST:
  PRINT Testaa BLOCKED ehto
  IF BLOCKED GOTO BLOCKEDTRUE
  PRINT BLOCKED false
  GOTO NOTBLOCKEDTEST
  
BLOCKEDTRUE:
  PRINT BLOCKED true
  
NOTBLOCKEDTEST:
  IF NOT BLOCKED GOTO NOTBLOCKEDTRUE
  PRINT NOT BLOCKED false
  GOTO MOVINGCONDTEST
  
NOTBLOCKEDTRUE:
  PRINT NOT BLOCKED true

MOVINGCONDTEST:
  PRINT Testaa MOVING ehto kunnolla
  IF MOVING GOTO MOVINGCONDTRUE
  PRINT MOVING ehto false
  GOTO NOTMOVINGCONDTEST
  
MOVINGCONDTRUE:
  PRINT MOVING ehto true
  
NOTMOVINGCONDTEST:
  IF NOT MOVING GOTO NOTMOVINGCONDTRUE
  PRINT NOT MOVING false
  GOTO LOADCMDTEST
  
NOTMOVINGCONDTRUE:
  PRINT NOT MOVING true

LOADCMDTEST:
  PRINT LOAD komennon testaus
  LOAD
  WAIT 1
  LOAD 5
  WAIT 1

UNLOADCMDTEST:
  PRINT UNLOAD komennon testaus
  UNLOAD
  WAIT 1
  UNLOAD 3
  WAIT 1

WAITCMDTEST:
  PRINT WAIT komennon testaus
  WAIT 1
  PRINT WAIT 3
  WAIT 3
  PRINT WAIT 5
  WAIT 5

MOVECMDTEST:
  PRINT MOVE komennon testaus
  PRINT MOVE 1
  MOVE
  PRINT MOVE 2
  MOVE
  PRINT MOVE 3
  MOVE

NOPTEST:
  PRINT NOP testaus
  NOP
  PRINT NOP jalkeen

GOTOTEST:
  PRINT GOTO hyppy
  GOTO GOTOTARGET
  PRINT Tama ei pitaisi tulostua
  
GOTOTARGET:
  PRINT GOTO toimii oikein

PRINTTEST:
  PRINT PRINT kaskyjen variantit
  PRINT Yksinkertainen viesti
  PRINT Viesti numeroilla 123 456
  PRINT Pitkä viesti yhteen riviin

COMMENTTEST:
  PRINT Kommentit testattu

FINISH:
  PRINT Kaikki testit valmis
  END
